version: '3.3'

services:
  httpserver:
    image: sqlchallenge:latest
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - '8000:8000'

    environment:
      - DB_CONN_STRING=mysql://root:123455@mysql:3306/sql_challenge
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DB_NAME=sql_challenge

    depends_on: 
      - mysql

  mysql:
    image: "bitnami/mysql:latest"
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=sql_challenge
      - MYSQL_MASTER_PORT_NUMBER=3306
      - ALLOW_EMPTY_PASSWORD=yes

    ports:
      - '3306:3306'

